name: protop
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.3
  - pytorch-cuda=12.1
  - torchvision
  - pip
  - pip:
      - pillow==9.1.1
      - timm==0.5.4
      - opencv-python==4.6.0.66
      - tensorboard==2.9.1
      - scipy==1.8.1
      - pandas==1.4.3
      - matplotlib==3.5.2
      - scikit-learn==1.1.1
